# Mapping of full claim text to short descriptive names
CLAIM_SHORTNAMES = {
    "After controlling for inflation and productivity growth, raising the federal minimum wage modestly does not consistently cause overall job losses.": "minimum-wage",
    "All forms of radiation exposure are dangerous at any level.": "radiation-danger",
    "Antarctica's recent gain in ice mass indicates that climate change has no impact on the continent": "antarctica-ice",
    "As of 2010, it was preferable to get sick in the United States than in Canada.": "us-vs-canada-healthcare",
    "As of 2010, religion was a force for good in the world.": "religion-force-for-good",
    "As of 2013, governments should tax the rich more.": "tax-the-rich",
    "As of 2014, state surveillance was a legitimate defense of our freedoms.": "surveillance-defense",
    "As of 2018, what critics called political correctness represented genuine progress.": "political-correctness",
    "As of 2019, China was a threat to the liberal international order.": "china-threat",
    "As of 2019, the capitalist system was broken and it was time to try something different.": "capitalism-broken",
    "As of 2022, AI will do more harm than good.": "ai-harm",
    "As of 2022, people should not trust mainstream media.": "mainstream-media-trust",
    "As of 2024, anti-Zionism is anti-Semitism.": "anti-zionism",
    "As of 2025, paying for sex should be a crime.": "paying-for-sex",
    "As of 2025, the United States started the new Cold War with Russia and provoked Russia's invasion of Ukraine.": "cold-war-russia",
    "Atmospheric carbon dioxide cannot warm the Earth's surface because heat only goes up": "co2-heat-up",
    "Be it resolved, AI research and development poses an existential threat.": "ai-existential-threat",
    "Claims that global cooling and warming periods followed by increased sea ice since 2007 disprove human-driven climate change are contradicted by extensive scientific evidence.": "sea-ice-climate",
    "Climate change has only had positive effects on global food production": "climate-food-positive",
    "Climate models have consistently overestimated global warming.": "climate-models-overestimate",
    "Cocoa production is improving and is not impacted by climate change": "cocoa-production",
    "Drinking raw milk is safer than pasteurized milk.": "raw-milk",
    "Fusion power plants are currently generating electricity for commercial grids.": "fusion-power",
    "GMOs have been banned throughout the entire European Union.": "gmo-eu-ban",
    "Genetically modified crops have been conclusively shown to cause cancer in humans.": "gmo-cancer",
    "Global deforestation rates have declined every year since 2000.": "deforestation-decline",
    "Globalization has undermined America's working class.": "globalization-working-class",
    "Greenhouse CO2 supplementation demonstrates that climate change is a scam": "greenhouse-co2-scam",
    "Higher taxes on the wealthy always reduce economic growth.": "wealthy-taxes-growth",
    "Homeopathic remedies have been shown in double-blind studies to outperform placebo for treating viral infections.": "homeopathy-studies",
    "Humans share more than 98% of their DNA with chimpanzees.": "human-chimp-dna",
    "Nicotine cures Parkinson's, Alzheimer's, hypothyroidism, and brain tumors": "nicotine-cures",
    "RFK Jr. misrepresented a large Danish study's findings on aluminum-containing vaccines, falsely claiming it provides calamitous evidence of harm including autism.": "rfk-vaccine-study",
    "The 2020 U.S. presidential election was proven to have widespread voter fraud affecting the outcome.": "2020-election-fraud",
    "The Health Ministry has issued warnings on samosa and jalebi similar to those for cigarettes.": "samosa-jalebi-warning",
    "The One Big Beautiful Bill Act, signed into law in July 2025, is falsely claimed by President Trump to prevent deaths and improve health insurance coverage, despite analysis showing it will lead to at least 42,500 preventable deaths annually due to changes in Medicaid and the Affordable Care Act.": "beautiful-bill-act",
    "The United Kingdom Meteorological Office (the Met Office) is accused of fabricating data for closed weather stations by estimating data with well-correlated neighboring stations, a practice scrutinized by bloggers.": "met-office-data",
    "The human population exceeded eight billion people in 2022.": "population-8-billion",
    "Universal basic income trials have shown no measurable economic effects.": "ubi-effects"
}
